services:
  aniliberty-indexer:
    image: ghcr.io/retrilzzy/aniliberty-indexer:latest
    container_name: aniliberty-indexer
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT:-3649}:${PORT:-3649}"
