services:
  aniliberty-indexer:
    image: ghcr.io/retrilzzy/aniliberty-indexer:latest
    container_name: aniliberty-indexer
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - HOST=${HOST:-0.0.0.0}
      - PORT=${PORT:-3649}
      - API_KEY=${API_KEY:-}
    ports:
      - "${PORT:-3649}:${PORT:-3649}"
